# Site settings 配置站点
title: "Ivan Jobs' Blog"
description: 'Ivan，非典型程序员，C++工程师/数学爱好者/马拉松跑者，热爱技术和运动。很高兴能在这里与你分享我对技术和生活的思考。'
keyword: 'Ivan, 数学, marathon, C++, ClickHouse, Mesos, Ceph, 经济学'
url: 'https://ivanjobs.github.io' # your host

# if you don't need baseurl, you should leave this value blank.
baseurl: ''

# Navigation links
nav:
  home: '/'
  tags: '/tags.html'

# Author 配置博主信息
author: 'Ivan'
nickname: 'Ivan'
bio: 'C++后端工程师，热爱技术&运动'
avatar: '/assets/img/head.jpg'

# Search
search: true

# Night mode
nightMode: true

# Comments
disqus: false
disqus_url: 'https://ivanjobs.disqus.com/embed.js'

# Share
social-share: true
social-share-items: ['wechat', 'github']

# theme color 主题皮肤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings 配置社交网站url: weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  github: '//github.com/ivanjobs'

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

RSS: false

# Plugins
gems: [jekyll-paginate]
