# Site settings
permalink: /blog/:year/:month/:title.html
title: Ivan Jobs' Blog 
description: > # this means to ignore newlines until "baseurl:"
  Ivan Jobs' Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ivanjobs.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

paginate: 20
paginate_path: "blog/page:num"
